# Teaching content for the Math section. Counts are filled in by mbuild.py from the bank.
DOMAINS = [
  {"id": "alg", "name": "Algebra", "spec": "About 35% of the test: 13 to 15 of the 44 questions",
   "blurb": "Straight lines in every costume: equations, functions, word problems, systems and inequalities.",
   "skills": ["le1", "lf", "le2", "sys", "inq"]},
  {"id": "adv", "name": "Advanced Math", "spec": "About 35% of the test: 13 to 15 of the 44 questions",
   "blurb": "Curves: parabolas, exponential growth, square roots, and rewriting expressions.",
   "skills": ["eqx", "nle", "nlf"]},
  {"id": "psda", "name": "Problem-Solving and Data Analysis", "spec": "About 15% of the test: 5 to 7 of the 44 questions",
   "blurb": "Rates, percentages, tables, graphs and chance: arithmetic with a story attached.",
   "skills": ["rat", "pct", "1vd", "2vd", "prb", "inf", "stc"]},
  {"id": "geo", "name": "Geometry and Trigonometry", "spec": "About 15% of the test: 5 to 7 of the 44 questions",
   "blurb": "Area and volume, angles, right triangles, and circles.",
   "skills": ["av", "lat", "rtt", "cir"]},
]

SKILLS = {
"le1": {"name": "Linear equations in one variable", "short": "One-variable equations",
  "idea": "One unknown, one equation. Peel the layers off the letter in reverse order until it stands alone.",
  "plain": "An equation is a balance scale. Whatever you do to one side, do to the other, and the scale stays level. Undo the last thing that was done to x first: if x was multiplied by 3 and then had 5 added, subtract the 5 before you divide by 3.",
  "steps": ["Clear brackets: multiply out anything in parentheses.", "Move every x-term to one side and every plain number to the other.", "Divide by the number in front of x.", "Read the last line of the question again. If it asks for 2x or x + 4, do that last step."],
  "example": {"q": "If 5(x − 3) + 2 = 3x + 7, what is the value of x?",
     "lines": ["5x − 15 + 2 = 3x + 7   (multiply out the bracket)", "5x − 13 = 3x + 7", "2x − 13 = 7   (take 3x from both sides)", "2x = 20   (add 13)", "x = 10   (divide by 2)"],
     "check": "Check: 5(7) + 2 = 37 and 3(10) + 7 = 37. Both sides match."},
  "trap": "The extra step. “If 3x + 7 = 19, what is x + 4?” x is 4, and 4 is a choice; the answer is 8.",
  "tip": "“No solution” and “infinitely many solutions” are not solving questions: line up the two sides and compare them (see the question type below)."},
"lf": {"name": "Linear functions", "short": "Linear functions",
  "idea": "A linear function adds the same amount every time x goes up by 1. Two numbers describe it: the slope m and the starting value b.",
  "plain": "f(x) is a machine: put a number in, one number comes out. f(4) means “feed it a 4”. In y = mx + b, m is the amount added per step (it follows words like per, each, every) and b is the amount you start with (a flat fee, a starting balance).",
  "steps": ["Find the starting amount: that is b.", "Find the per-step amount: that is m.", "Write y = mx + b and say what x counts.", "Put in the number you were given, or set y equal to the target and solve."],
  "example": {"q": "A gym charges a $40 joining fee plus $25 a month. What is the cost of 6 months?",
     "lines": ["Starting amount b = 40, per month m = 25", "c(m) = 25m + 40", "c(6) = 25(6) + 40 = 150 + 40 = 190"],
     "check": "Six months of fees is $150, plus the $40 fee: $190."},
  "trap": "Slope and starting value swapped. Both numbers are in the question and both are in the choices. Check the units: the slope is “dollars per month”, the start is just “dollars”.",
  "tip": "From a table, any two rows give the slope: change in y ÷ change in x. Walk the table back to x = 0 to read b."},
"le2": {"name": "Linear equations in two variables", "short": "Lines and their equations",
  "idea": "The same straight line, written in whatever form is least convenient. Convert it, read the slope, and know what parallel and perpendicular do.",
  "plain": "Slope is steepness: how far up for each step across. Parallel lines climb at the same rate, so they have the same slope. Perpendicular lines meet at a right angle; their slopes are negative reciprocals (flip the fraction and change the sign), so the two slopes multiply to −1.",
  "steps": ["If the line is in the form Ax + By = C, its slope is −A/B.", "Parallel: copy the slope. Perpendicular: flip and change the sign.", "x-intercept: put y = 0. y-intercept: put x = 0.", "To test a point, put its x and y into the equation."],
  "example": {"q": "Line ℓ is 3x + 4y = 12. Line k is perpendicular to ℓ. What is the slope of k?",
     "lines": ["Slope of ℓ = −A/B = −3/4", "Perpendicular: flip and change sign → 4/3"],
     "check": "Check: (−3/4)(4/3) = −1."},
  "trap": "The negative reciprocal done halfway: flipping without changing the sign, or the reverse. Both halfway answers are offered.",
  "tip": "In a word problem like 5x + 8y = 200, the numbers in front of x and y are prices or rates, and 200 is the total."},
"sys": {"name": "Systems of two linear equations", "short": "Systems of equations",
  "idea": "Two lines. They cross once, never meet (parallel), or are the same line. You can tell which without solving.",
  "plain": "A solution to a system is a point on both lines at once. Lines can do only three things: cross once (one solution), run side by side (no solution) or sit on top of each other (infinitely many).",
  "steps": ["To find the crossing point: add or subtract the equations so one letter disappears, then solve for the other.", "Put that value back in to get the second letter.", "Read the question again: it often wants x + y, 2x, or only y.", "On a hard one, graph both lines in Desmos and click the crossing point."],
  "example": {"q": "3x + 2y = 19 and x − 2y = 1. What is x + y?",
     "lines": ["Add the equations: 4x = 20, so x = 5", "5 − 2y = 1, so y = 2", "x + y = 7"],
     "check": "Check: 3(5) + 2(2) = 19 and 5 − 2(2) = 1. Both 5 and 2 are offered as choices; the answer is 7."},
  "trap": "Answering with x when the question asks for x + y. You did the work right and stopped one step early.",
  "tip": "If the question wants x + y, try adding the two equations first; the total often falls out in one line."},
"inq": {"name": "Linear inequalities", "short": "Inequalities",
  "idea": "An equation names one value; an inequality names a whole range. Often you can test a number instead of solving.",
  "plain": "Everything works like an equation, with one exception: multiplying or dividing both sides by a negative number flips the sign, because it mirrors the number line.",
  "steps": ["Translate the words: at least ≥, at most ≤, more than >, fewer than <, no more than ≤.", "For “which inequality represents…”, test a number that clearly should work and one that clearly should not.", "For “greatest number” questions, solve, then round in the direction the story allows (you cannot buy 12.6 tickets).", "On a graph, a solid line means ≤ or ≥; a dashed line means < or >."],
  "example": {"q": "Small boxes weigh 20 lb, large boxes 50 lb, and a van carries at most 1,000 lb. Which inequality fits?",
     "lines": ["20s + 50ℓ ≤ 1000", "Test 10 and 10: 700 ≤ 1000, allowed", "Test 20 and 15: 1150 ≤ 1000, rejected"],
     "check": "The inequality behaves the way the van does."},
  "trap": "“At most” read as “at least”, and a sign not flipped after dividing by a negative. Both mirror-image answers are offered.",
  "tip": "In a “greatest number of …” question, the exact answer is often a decimal. Round down if you cannot exceed the limit."},
"eqx": {"name": "Equivalent expressions", "short": "Rewriting expressions",
  "idea": "Two expressions are equivalent when they give the same answer for every x. You rewrite; you never solve.",
  "plain": "An expression has no equals sign, so there is nothing to solve. The question asks for a different-looking recipe that always gives the same result.",
  "steps": ["Multiply out brackets and combine like terms; or factor (common factor first, then difference of squares, then the trinomial).", "Exponents: xᵃ·xᵇ = xᵃ⁺ᵇ, (xᵃ)ᵇ = xᵃᵇ, x⁻ᵃ = 1/xᵃ, x^(a/b) = the b-th root of xᵃ.", "Stuck? Pick a number: put x = 2 into the question and into each choice. The choice that matches is the answer.", "Constants to find? Expand both sides and match the x² parts, the x parts and the plain numbers."],
  "example": {"q": "Which is equivalent to x² + 7x + 12? A (x+2)(x+6)  B (x+3)(x+4)  C (x+1)(x+12)  D (x−3)(x−4)",
     "lines": ["Pick x = 2: 4 + 14 + 12 = 30", "A: 4×8 = 32   B: 5×6 = 30   C: 3×14 = 42   D: (−1)(−2) = 2", "Only B gives 30"],
     "check": "Factoring gives the same answer: two numbers that multiply to 12 and add to 7 are 3 and 4."},
  "trap": "The outside power not applied to the number in front: (2x³)⁴ is 16x¹², not 2x¹².",
  "tip": "Avoid 0 and 1 when you pick a number: many different expressions agree there. Picking a number only works when there are choices to test; on a grid-in, rewrite instead."},
"nle": {"name": "Nonlinear equations and systems", "short": "Nonlinear equations",
  "idea": "Same unwrapping as a linear equation, but the letter is squared, under a root or in a fraction. Squaring can create false answers, so check yours.",
  "plain": "Squaring loses a sign: 3 and −3 both square to 9, so x² = 9 has two answers. Squaring both sides of an equation can add an answer that never worked. That is why you put your answers back into the original equation.",
  "steps": ["Get everything on one side so it equals 0.", "Factor, or use the quadratic formula x = (−b ± √(b² − 4ac)) / 2a.", "If you squared both sides or cleared a fraction, check each answer in the original equation.", "Apply any condition in the question: positive, negative, the greater one."],
  "example": {"q": "What is the solution to √(x + 6) = x?",
     "lines": ["Square both sides: x + 6 = x²", "x² − x − 6 = 0, so (x − 3)(x + 2) = 0", "x = 3 or x = −2", "Check x = −2: √4 = 2, not −2. Reject it."],
     "check": "Only x = 3 works. The rejected −2 is a listed choice."},
  "trap": "The extra root. When the question says “the positive solution”, both roots are in the choices.",
  "tip": "“In terms of” questions want a formula, not a number. Check your rearrangement by putting in easy numbers."},
"nlf": {"name": "Nonlinear functions", "short": "Nonlinear functions",
  "idea": "The biggest skill on the test. Almost everything here is a parabola (from squaring) or an exponential curve (from repeated multiplying).",
  "plain": "A parabola is a symmetric U. Its turning point, the vertex, is where the maximum or minimum sits, exactly halfway between the two places it crosses the x-axis. Exponential growth multiplies by the same number each step: grows 8% means ×1.08, shrinks 15% means ×0.85.",
  "steps": ["Know the three forms of a parabola: y = a(x − h)² + k shows the vertex (h, k); y = a(x − p)(x − q) shows the zeros p and q; y = ax² + bx + c shows the y-intercept c.", "No vertex form? The vertex is at x = −b/(2a); put that x back in for the y-value.", "Exponential: y = a·bˣ. a is the starting amount; b is the multiplier per step.", "When a change happens every n years, the exponent is x/n."],
  "example": {"q": "f(x) = x² − 6x + 5. What is the minimum value of f?",
     "lines": ["Zeros: (x − 1)(x − 5), so x = 1 and x = 5", "Vertex halfway: x = 3", "f(3) = 9 − 18 + 5 = −4"],
     "check": "The minimum value is −4, and it happens at x = 3. Both 3 and −4 are choices; the question asked for the value."},
  "trap": "The x of the vertex when the question asked for the maximum or minimum value, and the reverse. Say the sentence: “the minimum is −4, at x = 3”.",
  "tip": "Desmos marks a parabola’s vertex and zeros as grey points; click them. That turns most hard vertex questions into a quick read."},
"rat": {"name": "Ratios, rates, proportions and units", "short": "Ratios, rates and units",
  "idea": "A rate is a fraction with units on top and bottom. Write the units in and cancel them like numbers, and the setup checks itself.",
  "plain": "“Per” means “divided by”. 60 miles per hour is 60 miles ÷ 1 hour. When you convert, multiply by fractions arranged so the unit you want to lose appears once on top and once on the bottom.",
  "steps": ["Write what you have as a fraction with its units.", "Multiply by conversion fractions so unwanted units cancel.", "Stop when only the units the question asks for are left.", "Proportions: put the same kind of thing on top on both sides, then cross-multiply."],
  "example": {"q": "A space station travels 4.76 miles per second. How many miles per hour is that?",
     "lines": ["(4.76 miles / 1 second) × (3,600 seconds / 1 hour)", "Seconds cancel", "4.76 × 3,600 = 17,136 miles per hour"],
     "check": "If you divide by 3,600 instead, the units come out as nonsense. The unit check catches it."},
  "trap": "Square and cubic units: 1 foot is 12 inches, but 1 square foot is 144 square inches and 1 cubic foot is 1,728 cubic inches.",
  "tip": "Density = mass ÷ volume. Population density = people ÷ area. Same idea, different units."},
"pct": {"name": "Percentages", "short": "Percentages",
  "idea": "Percent means “out of 100”. Every percentage question turns on one thing: the percent of what?",
  "plain": "30% is 30/100 is 0.30. “Is” means equals, “of” means times, “what” is the unknown. Going up 20% means multiplying by 1.20; going down 20% means multiplying by 0.80.",
  "steps": ["Translate in reading order: “24 is what percent of 80” → 24 = (p/100) × 80.", "Percent change = (new − old) ÷ old. Always divide by the old value.", "Several changes in a row: multiply the multipliers. Never add the percents.", "Working back to an original: divide by the multiplier (after 15% off, price ÷ 0.85)."],
  "example": {"q": "A $200 jacket goes up 20%, then down 20%. What is the final price?",
     "lines": ["200 × 1.20 = 240", "240 × 0.80 = 192", "Or at once: 1.20 × 0.80 = 0.96, a 4% net drop"],
     "check": "The two 20% changes do not cancel: the drop is taken from a bigger number."},
  "trap": "Dividing by the new value instead of the old one, and adding percents (20% up then 20% down is not zero).",
  "tip": "a% of b equals b% of a. 4% of 75 is 75% of 4, which is 3."},
"1vd": {"name": "One-variable data: center and spread", "short": "Mean, median and spread",
  "idea": "The mean is the balance point and gets dragged by extreme values. The median is the middle value and ignores them.",
  "plain": "Add 5 to every value and the mean and median both go up by 5, but the range and standard deviation do not change: the gaps between values are the same. Standard deviation is never calculated on the test, only compared: tight cluster means small, spread out means large.",
  "steps": ["Median: put the values in order, then count to the middle position, (n + 1) ÷ 2.", "Mean: total ÷ count. When a value is added or removed, work with totals: mean × count = total.", "Range: largest − smallest.", "From a frequency table, the values are the categories; the frequencies are how many times each appears."],
  "example": {"q": "Households (15 in all) own 0, 1, 2, 3 or 4 pets, with frequencies 2, 5, 4, 3, 1. What is the median?",
     "lines": ["Middle position: (15 + 1) ÷ 2 = 8th", "0 pets fill positions 1–2, 1 pet fills 3–7, 2 pets fill 8–11", "The 8th value is 2"],
     "check": "The median is 2 pets. Do not answer with a frequency."},
  "trap": "Answering with a frequency (how many households) instead of a value (how many pets).",
  "tip": "Five numbers average 12; what sixth number makes the average 14? Totals: 6 × 14 − 5 × 12 = 84 − 60 = 24."},
"2vd": {"name": "Two-variable data: models and scatterplots", "short": "Scatterplots and models",
  "idea": "The line of best fit answers almost every question here. The dots are there to make wrong answers.",
  "plain": "A scatterplot shows one dot per case. The line of best fit is the trend. “Predicted” or “estimated” means read the line, not a dot. A straight-looking cloud is a linear model; one that bends upward faster and faster is exponential.",
  "steps": ["Predicted value: find x on the bottom axis, go up to the line, read across.", "Slope: the change in y for each 1 added to x, with units.", "Linear or exponential: equal differences mean linear; equal ratios mean exponential.", "Average rate of change between two points: change in y ÷ change in x."],
  "example": {"q": "A line of best fit is y = 2.5x + 10. What does it predict when x = 8?",
     "lines": ["y = 2.5(8) + 10", "y = 20 + 10 = 30"],
     "check": "A dot near x = 8 might sit at 28 or 32; the prediction comes from the line."},
  "trap": "Reading a dot instead of the line; misreading the scale on the axes.",
  "tip": "Read the axis labels and the size of one grid square before you read any value."},
"prb": {"name": "Probability and conditional probability", "short": "Probability",
  "idea": "A probability is a fraction. The whole skill is choosing the right number for the bottom.",
  "plain": "Probability = the outcomes you want ÷ all the outcomes in the group. Words like “given that”, “of those who” and “among the seniors” shrink the group: the bottom becomes that row or column total, not the grand total.",
  "steps": ["Underline the group the question names: everyone, or only one row or column?", "The bottom of the fraction is that group’s total.", "The top is the cell that is in that group and has the feature asked about.", "Check the answer form: fraction, decimal, or percent."],
  "example": {"q": "Of 160 students, 75 prefer cats; 45 of those are seniors. A cat-lover is picked at random. What is the probability the student is a senior?",
     "lines": ["The group is the 75 cat-lovers", "45 ÷ 75 = 3/5 = 0.6"],
     "check": "45 ÷ 160 would answer a different question (a random student who is a senior and prefers cats)."},
  "trap": "Using the grand total when the question restricted you to one row or column.",
  "tip": "Expected count = probability × total. A 0.35 chance among 60 marbles means 21 marbles."},
"inf": {"name": "Inference from samples and margin of error", "short": "Samples and margin of error",
  "idea": "A sample estimate plus or minus the margin of error gives a range of believable values for the whole population.",
  "plain": "If 62% of a random sample agree, with a margin of error of 4%, the true figure is plausibly anywhere from 58% to 66%. Bigger samples give smaller margins of error.",
  "steps": ["Range = estimate − margin to estimate + margin.", "A conclusion must use the range, not one exact number.", "Scale up from a random sample: sample share × population size.", "Larger random sample → smaller margin of error."],
  "example": {"q": "A random sample of 400 city adults: 62% support a plan, margin of error 4%. Which conclusion is best?",
     "lines": ["Range: 58% to 66%", "It applies to adults in this city only"],
     "check": "“Exactly 62%” and “adults in the whole country” are both wrong."},
  "trap": "Treating the estimate as exact, or applying it to a bigger group than the one sampled.",
  "tip": "If two samples are taken the same way, the larger one has the smaller margin of error."},
"stc": {"name": "Evaluating statistical claims", "short": "Study design",
  "idea": "Two kinds of random. Random selection lets you generalize to the population sampled. Random assignment lets you claim cause and effect.",
  "plain": "Pick people at random from a group, and the results describe that group and nobody else. Randomly decide who gets a treatment, and you can say the treatment caused the difference. Without random assignment you can only report a link.",
  "steps": ["Who was sampled, and was it random? That is the largest group you can generalize to.", "Were subjects randomly assigned to treatments? Only then can you claim cause.", "A survey of volunteers or of one special place does not represent everyone.", "Watch for samples that are biased by where or how they were taken."],
  "example": {"q": "A random sample of students at one school tried a game, and their scores improved. To whom do the results apply?",
     "lines": ["Random selection from students at that school", "So: students at that school, not all students everywhere"],
     "check": "Choices that name a bigger population are wrong however good the numbers are."},
  "trap": "Generalizing past the group that was sampled. It is offered in almost every one of these questions.",
  "tip": "This skill has only 12 questions in the bank, but 7 are Hard; the rule above settles most of them."},
"av": {"name": "Area and volume", "short": "Area and volume",
  "idea": "The formulas are printed on the reference sheet. Most questions give you the area or volume and ask for a length.",
  "plain": "Area counts unit squares; volume counts unit cubes. A prism or cylinder is its base area times its height. A cone or pyramid is one third of that.",
  "steps": ["Find the shape’s formula on the reference sheet.", "Put in everything you know, including the area or volume if it is given.", "Solve for the missing length.", "Scale: multiply every length by k and areas multiply by k², volumes by k³."],
  "example": {"q": "A cone has volume 48π cubic feet and height 9 feet. What is its radius?",
     "lines": ["V = (1/3)πr²h", "48π = (1/3)πr²(9) = 3πr²", "r² = 16, so r = 4"],
     "check": "Check: (1/3)π(16)(9) = 48π."},
  "trap": "Using the diameter where the radius belongs, and dropping the 1/3 from a cone or pyramid.",
  "tip": "Shaded region = whole shape − the part cut out."},
"lat": {"name": "Lines, angles and triangles", "short": "Angles and triangles",
  "idea": "A short list of angle rules does almost all the work. Learn the list and this is the most mechanical skill on the test.",
  "plain": "Where two lines cross, opposite angles are equal and side-by-side angles add to 180°. When a line crosses two parallel lines, the same set of angles repeats at both crossings. A triangle’s angles add to 180°. Similar triangles have the same angles, so their sides are in proportion.",
  "steps": ["Mark every angle you know on the figure.", "Use: vertical angles equal; straight line 180°; triangle 180°; around a point 360°.", "Parallel lines: corresponding and alternate angles are equal; same-side interior angles add to 180°.", "Similar triangles: find the scale factor from one pair of matching sides, then apply it."],
  "example": {"q": "Two similar triangles: sides 6 and 8 in the first, 9 and x in the second. What is x?",
     "lines": ["Scale factor: 9 ÷ 6 = 1.5", "x = 8 × 1.5 = 12"],
     "check": "Proportion check: 6/9 = 8/12."},
  "trap": "Matching the wrong sides in similar triangles. Match sides by the angles they face.",
  "tip": "An exterior angle of a triangle equals the sum of the two inside angles not next to it."},
"rtt": {"name": "Right triangles and trigonometry", "short": "Right triangles and trig",
  "idea": "Mostly Hard, but most of it collapses if you spot a familiar triangle before calculating.",
  "plain": "Pythagoras: a² + b² = c², where c is the side across from the right angle. sin = opposite ÷ hypotenuse, cos = adjacent ÷ hypotenuse, tan = opposite ÷ adjacent. The two small angles add to 90°, so the sine of one equals the cosine of the other.",
  "steps": ["Look for a known triangle: 3-4-5, 5-12-13, 8-15-17, 7-24-25 and their multiples.", "Special triangles (on the reference sheet): 45-45-90 is 1 : 1 : √2; 30-60-90 is 1 : √3 : 2.", "Label opposite and adjacent from the angle you are using.", "sin(x°) = cos(90° − x°)."],
  "example": {"q": "Right triangle ABC, right angle at C, AC = 9 and BC = 12. Find AB and sin A.",
     "lines": ["9 and 12 are 3 and 4 times 3, so AB = 15", "sin A = opposite ÷ hypotenuse = 12/15 = 4/5"],
     "check": "Check: 81 + 144 = 225 = 15²."},
  "trap": "Opposite and adjacent read from the wrong angle; sine and cosine swapped.",
  "tip": "If a question gives sin of one small angle and asks for cos of the other, the answer is the number you were given."},
"cir": {"name": "Circles", "short": "Circles",
  "idea": "About 6 in 10 circle questions are about the circle’s equation in the xy-plane. The rest are arcs, radians and tangent lines.",
  "plain": "(x − h)² + (y − k)² = r² is Pythagoras for every point on the circle: center (h, k), radius r. If the equation comes multiplied out, complete the square. An arc is a fraction of the whole circle: (angle ÷ 360) × circumference. 180° is π radians.",
  "steps": ["Read the center from the brackets, changing each sign: (x − 3)² means x = 3; (y + 4)² means y = −4.", "The right side is r², not r: 36 means radius 6.", "Expanded equation: halve the x-number and square it; do the same for y; add both to each side.", "Arcs and sectors: (central angle ÷ 360°) × the whole circumference or area."],
  "example": {"q": "x² + y² − 6x + 8y − 11 = 0. What are the center and radius?",
     "lines": ["(x² − 6x) + (y² + 8y) = 11", "Add 9 and 16: (x − 3)² + (y + 4)² = 36", "Center (3, −4), radius 6"],
     "check": "Check a point: (3, 2) is 6 above the center. (0)² + (6)² = 36."},
  "trap": "Reporting r² as the radius (36 instead of 6), and reversing the signs of the center.",
  "tip": "A radius drawn to the point where a tangent line touches meets that line at 90°."},
}

# Question types: name, what you see, steps, trap, tip (optional), desmos (optional)
TYPES = {
# ---- le1
"le1-solve": {"name": "Solve the equation", "spot": "“What value of x is the solution…?” or “If …, what is the value of …?”",
  "steps": ["Multiply out brackets; clear fractions by multiplying both sides by the bottom number.", "Get x-terms on one side, numbers on the other.", "Divide. Then check the question asks for x and not something built from x."],
  "trap": "The value of x offered when the question asked for an expression such as 3x − 2."},
"le1-count": {"name": "How many solutions? (one variable)", "spot": "“How many solutions…”, “no solution”, “infinitely many solutions”, often with a constant to find.",
  "steps": ["Simplify both sides to the form ax + b.", "Same x-number and same plain number: infinitely many solutions.", "Same x-number, different plain number: no solution.", "Different x-numbers: exactly one solution."],
  "trap": "Trying to solve for x. With matching x-parts, x cancels and there is nothing to find.",
  "tip": "To find a constant: set the x-numbers equal (and the plain numbers equal for “infinitely many”, unequal for “no solution”)."},
"le1-model": {"name": "Build the equation from a story", "spot": "“Which equation represents this situation?”",
  "steps": ["Name the unknown in words.", "Write each sentence of the story as a piece of the equation.", "Test a choice with small easy numbers from the story if two look alike."],
  "trap": "A choice that uses the right numbers in the wrong places (rate and fixed amount swapped)."},
"le1-word": {"name": "One-step story problem", "spot": "A short story with one unknown: books shared out, a perimeter, a total cost.",
  "steps": ["Write one equation from the story.", "Solve it.", "Check the answer makes sense in the story (a whole number of people, a positive length)."],
  "trap": "Answering with an in-between number, such as the total before the last step."},
# ---- lf
"lf-eval": {"name": "Evaluate the function", "spot": "“The function f is defined by … What is f(3)?” or “For what value of x does f(x) = 10?”",
  "steps": ["f(3): put 3 wherever x appears and work it out.", "f(x) = 10: set the formula equal to 10 and solve for x."],
  "trap": "Mixing up the input and the output: f(3) is an output; “f(x) = 3” gives an input."},
"lf-model": {"name": "Linear model from a story", "spot": "Fees, rates, “per”, “each”: “Which function gives the total cost…?”",
  "steps": ["The one-time amount is b.", "The amount per unit is m.", "Write y = mx + b; check a value against the story."],
  "trap": "Fixed amount and rate swapped; a rate that should only start after the first hour or day."},
"lf-interpret": {"name": "What does this number mean?", "spot": "“What is the best interpretation of 25 in this context?”",
  "steps": ["Is the number multiplied by x? Then it is the change per one unit of x (slope).", "Is it on its own? Then it is the value when x = 0 (starting value).", "Pick the choice with matching units."],
  "trap": "A choice that describes the starting value when the number is the rate, or the reverse."},
"lf-intercept": {"name": "Find an intercept", "spot": "“What is the x-intercept / y-intercept of the graph of f?”",
  "steps": ["y-intercept: set x = 0.", "x-intercept: set y (or f(x)) = 0 and solve.", "From a graph or table, read where the line crosses the axis."],
  "trap": "x- and y-intercepts swapped. Both points are offered."},
"lf-table": {"name": "Linear function from a table", "spot": "A table of x and f(x) values.",
  "steps": ["Slope = change in f(x) ÷ change in x between any two rows.", "Walk back to x = 0, or put one row into y = mx + b, to find b.", "Check the formula on a third row."],
  "trap": "Using one row’s ratio y/x as the slope."},
"lf-graph": {"name": "Linear function from a graph", "spot": "“The graph of the linear function f is shown.”",
  "steps": ["Find two points where the line crosses grid corners exactly.", "Slope = rise ÷ run between them.", "Read b where the line crosses the y-axis."],
  "trap": "Misreading the scale: check what one grid square is worth on each axis."},
"lf-build": {"name": "Line through given points", "spot": "“The graph contains the points (…) and (…). Which equation defines f?”",
  "steps": ["Slope = (y₂ − y₁) ÷ (x₂ − x₁).", "Put one point into y = mx + b to find b.", "Test the other point in your answer."],
  "trap": "Subtracting the coordinates in different orders on top and bottom."},
# ---- le2
"le2-parallel": {"name": "Parallel and perpendicular lines", "spot": "“Line k is parallel / perpendicular to line ℓ…”",
  "steps": ["Get the slope of the given line (from y = mx + b, or −A/B from Ax + By = C).", "Parallel: same slope. Perpendicular: flip and change the sign.", "If a point is given, use it to find b."],
  "trap": "Flipping without changing the sign, or changing the sign without flipping."},
"le2-model": {"name": "Two-variable equation from a story", "spot": "“Which equation represents this situation?” with two kinds of items and a total.",
  "steps": ["Each kind: price (or size) × how many.", "Add them and set equal to the total.", "Check which letter stands for which item."],
  "trap": "The prices attached to the wrong letters."},
"le2-interpret": {"name": "Meaning of a number in a two-variable equation", "spot": "“What is the best interpretation of 8 in this context?”",
  "steps": ["See what the number multiplies: it is the amount per one of those.", "A number on the other side of the equals sign is usually the total.", "Match the units in the choices."],
  "trap": "A choice that swaps the meaning of the two letters."},
"le2-intercept": {"name": "Slope and intercepts of a line", "spot": "“What is the slope…?”, “What is the y-intercept…?” of a given equation.",
  "steps": ["Rewrite as y = mx + b, or use slope = −A/B from Ax + By = C.", "y-intercept: put x = 0. x-intercept: put y = 0."],
  "trap": "Reading the coefficient of x as the slope before y is on its own."},
"le2-point": {"name": "Points, tables and graphs of a line", "spot": "“Which table…”, “What is an equation of the graph shown?”, “The point (a, 5) lies on the line…”",
  "steps": ["A point is on a line if its x and y make the equation true.", "For a graph, read two exact points and find the slope and intercept.", "For tables, test one row in each choice; one wrong row rules a choice out."],
  "trap": "A table where only some rows fit."},
"le2-solve": {"name": "Use the given equation", "spot": "A two-variable equation from a story, and the value of one letter.",
  "steps": ["Put the known value in.", "Solve for the other letter."],
  "trap": "Putting the value in for the wrong letter."},
# ---- sys
"sys-solve": {"name": "Solve the system", "spot": "“The solution to the given system is (x, y). What is the value of …?”",
  "steps": ["Line up the equations. If one letter has matching or opposite numbers, add or subtract to remove it.", "Otherwise get one letter alone and substitute it into the other equation.", "Answer exactly what is asked: x, y, x + y, 2x − y."],
  "trap": "Giving x when the question asked for y or for x + y.",
  "desmos": "Type both equations and click the crossing point."},
"sys-count": {"name": "How many solutions? (system)", "spot": "“No solution”, “infinitely many solutions”, “exactly one solution”, often “where k is a constant”.",
  "steps": ["Write both equations as Ax + By = C.", "Compare A₁/A₂ with B₁/B₂: different means exactly one solution.", "Same, but C₁/C₂ different: no solution (parallel lines).", "All three the same: infinitely many (the same line)."],
  "trap": "Starting to solve. These questions are built so that solving wastes time.",
  "tip": "Same slope, different intercept = no solution. Same slope, same intercept = infinitely many."},
"sys-model": {"name": "Build the system from a story", "spot": "“Which system of equations could be used to find…?”",
  "steps": ["One equation counts things (how many in total).", "The other counts money, weight or points.", "Check that each number sits beside the right letter."],
  "trap": "A system where the count equation uses the prices."},
"sys-graph": {"name": "System on a graph", "spot": "“The graph of a system is shown. What is the solution?” or “At how many points do the graphs intersect?”",
  "steps": ["The solution is the point where the lines cross.", "Read it exactly from grid corners.", "Parallel lines never cross: no solution."],
  "trap": "Reading an intercept instead of the crossing point."},
"sys-word": {"name": "Two-unknown story problem", "spot": "Tickets of two prices, two mixtures, a total count and a total cost.",
  "steps": ["Write a count equation and a value equation.", "Solve (elimination is usually quickest).", "Answer the quantity asked about."],
  "trap": "Answering with the other unknown, which you also found."},
# ---- inq
"inq-model": {"name": "Write the inequality", "spot": "“Which inequality represents…?”",
  "steps": ["Translate: at least ≥, at most ≤, more than >, less than <.", "Build the expression for the total.", "Test an easy value that should be allowed."],
  "trap": "At least and at most swapped; the mirror-image choice is always there."},
"inq-maxmin": {"name": "Greatest or least number allowed", "spot": "“What is the greatest number of … possible?” “What is the minimum number…?”",
  "steps": ["Write the inequality from the story.", "Solve it as if it were an equation.", "Round in the direction the story allows: down for a maximum of whole items, up for a minimum."],
  "trap": "Rounding the wrong way (12.6 tickets allowed means 12, not 13)."},
"inq-point": {"name": "Which point or table satisfies it?", "spot": "“Which point is a solution…”, “For which table are all values solutions…?”",
  "steps": ["Put each point into the inequality.", "One failing row rules out a whole table."],
  "trap": "Treating the boundary as allowed when the sign is < or >."},
"inq-graph": {"name": "Shaded region", "spot": "“The shaded region represents the solutions to which inequality?”",
  "steps": ["Solid boundary: ≤ or ≥. Dashed: < or >.", "Test a point in the shaded region, such as (0, 0) if it is shaded."],
  "trap": "The right line with the wrong side shaded."},
# ---- eqx
"eqx-rewrite": {"name": "Which expression is equivalent?", "spot": "“Which expression is equivalent to …?”",
  "steps": ["Multiply out brackets and combine like terms, or factor.", "Watch every minus sign: −(x − 3) is −x + 3.", "Unsure? Put x = 2 into the original and each choice."],
  "trap": "A sign lost when multiplying out a bracket that starts with a minus.",
  "tip": "Picking a number works on every multiple-choice question of this type."},
"eqx-coef": {"name": "Match the coefficients", "spot": "“… is equivalent to ax² + bx + c, where a, b and c are constants. What is …?”",
  "steps": ["Expand the given side completely.", "Match the x² parts, the x parts and the plain numbers.", "Solve the small equations that result."],
  "trap": "Matching before expanding fully."},
"eqx-exp": {"name": "Exponents and roots", "spot": "Powers, roots or fractional exponents: “for all positive values of x…”",
  "steps": ["Write roots as fractional powers: the cube root of x⁴ is x^(4/3).", "Multiply: add exponents. Divide: subtract. Power of a power: multiply.", "Rewrite the answer in the form the choices use."],
  "trap": "Adding exponents when you should multiply them, or the reverse."},
"eqx-rational": {"name": "Fractions with x", "spot": "Fractions with x in the bottom.",
  "steps": ["Find a common bottom.", "Combine the tops.", "Simplify, and note values of x that are not allowed."],
  "trap": "Adding the bottoms together."},
# ---- nle
"nle-solve": {"name": "Solve a quadratic or other nonlinear equation", "spot": "“What is a solution to the given equation?”",
  "steps": ["Get 0 on one side.", "Factor, or use the quadratic formula.", "With choices: put each choice in; you need only one that works."],
  "trap": "Stopping at a factored form and reading the signs wrong: (x − 3) = 0 means x = 3."},
"nle-sign": {"name": "The positive (or negative) solution", "spot": "“What is the positive solution…?”, “the greater of the two…”",
  "steps": ["Find both solutions.", "Keep the one the question allows."],
  "trap": "The banned root is always one of the choices."},
"nle-literal": {"name": "Rearrange a formula (“in terms of”)", "spot": "“Which equation correctly expresses h in terms of V and r?”",
  "steps": ["Find what is attached to the target letter.", "Undo it step by step, doing the same to both sides.", "Check with easy numbers: pick values, compute, and see if your formula gives them back."],
  "trap": "Choosing a number. The answer is a formula."},
"nle-count": {"name": "How many real solutions?", "spot": "“How many distinct real solutions…”, “exactly one solution”, “no real solutions”.",
  "steps": ["Write the equation as ax² + bx + c = 0.", "Discriminant b² − 4ac: positive means two solutions, zero means one, negative means none.", "For a line and a parabola: substitute, then use the discriminant."],
  "trap": "Solving fully when only the number of solutions is asked."},
"nle-sum": {"name": "Sum or product of the solutions", "spot": "“What is the sum of the solutions…?”",
  "steps": ["Write as ax² + bx + c = 0.", "Sum of solutions = −b/a; product = c/a."],
  "trap": "Forgetting to divide by a when a is not 1.",
  "tip": "Almost all of these are rated Hard, and this one line answers them."},
"nle-system": {"name": "Line meets curve", "spot": "A system with a squared term, or “the graphs intersect at…”",
  "steps": ["Set the two expressions for y equal.", "Solve the quadratic.", "Put x back in to get y if asked."],
  "trap": "Giving the x-coordinate when the y-coordinate was asked.",
  "desmos": "Graph both and click the crossing points."},
"nle-radical": {"name": "Square roots and fractions", "spot": "An equation with √ or with x in a denominator.",
  "steps": ["Get the root alone, then square both sides (or multiply by the denominator).", "Solve.", "Check every answer in the original equation and throw out any that fail."],
  "trap": "Keeping an extraneous answer that only works in the squared equation."},
# ---- nlf
"nlf-eval": {"name": "Evaluate a nonlinear function", "spot": "“The function f is defined by … What is f(…)?”",
  "steps": ["Put the number in for x everywhere.", "Order of operations: powers before multiplying.", "For f(x + 2), replace every x with (x + 2)."],
  "trap": "f(x + 2) confused with f(x) + 2."},
"nlf-vertex": {"name": "Maximum, minimum and vertex", "spot": "“maximum”, “minimum”, “vertex”, “greatest value”, “reaches its minimum”.",
  "steps": ["Vertex form a(x − h)² + k: the vertex is (h, k).", "Otherwise x = −b/(2a), or halfway between the zeros.", "The maximum or minimum VALUE is the y-coordinate; it happens AT the x-coordinate."],
  "trap": "Giving the x of the vertex when the question wanted the value, or the reverse.",
  "desmos": "Graph it and click the grey vertex point."},
"nlf-exp": {"name": "Build the exponential model", "spot": "“increases by 8% each year”, “doubles every 3 days”, “decays”.",
  "steps": ["Start amount = a.", "Up p%: b = 1 + p/100. Down p%: b = 1 − p/100. Doubles: 2. Halves: 1/2.", "Every n units: exponent x/n."],
  "trap": "Using the rate (0.08) instead of the multiplier (1.08), or 0.15 instead of 0.85."},
"nlf-exp-int": {"name": "Meaning of an exponential model", "spot": "“What is the best interpretation of 1.06 in this context?”",
  "steps": ["The number in front is the starting value.", "The base b: above 1 grows by (b − 1)×100% per step; below 1 shrinks by (1 − b)×100%.", "Check what one step is (a year, a month)."],
  "trap": "Reading 1.06 as “increases by 106%”."},
"nlf-height": {"name": "Height over time", "spot": "An object launched, thrown or dropped; height in feet or meters after t seconds.",
  "steps": ["Height at a time: put in t.", "Hits the ground: set height = 0 and keep the positive t.", "Highest point: the vertex."],
  "trap": "The time of the highest point given when the height was asked."},
"nlf-interpret": {"name": "Meaning of a number in a nonlinear model", "spot": "“Which of the following is the best interpretation of …?”",
  "steps": ["Work out what the expression represents in the story (a length, a width, a count).", "Match the units."],
  "trap": "A choice describing a different part of the same formula."},
"nlf-zeros": {"name": "Zeros and x-intercepts", "spot": "“x-intercept”, “zeros of the function”, “factor of”.",
  "steps": ["Set f(x) = 0.", "In factored form a(x − p)(x − q), the zeros are p and q.", "If p is a zero, (x − p) is a factor."],
  "trap": "The sign flip: a factor (x + 4) means a zero at −4."},
"nlf-yint": {"name": "y-intercept and points on the graph", "spot": "“The graph has a y-intercept of …” or “passes through the point …”, often with constants.",
  "steps": ["y-intercept: put x = 0.", "A point on the graph: put its x and y into the equation to find the constant."],
  "trap": "Putting the point’s coordinates into the wrong letters."},
"nlf-graph": {"name": "Read a graph or table of a curve", "spot": "“The graph of f is shown…”, “Which table gives values for…?”",
  "steps": ["Read exact points from grid corners or table rows.", "Check intercepts and whether the curve opens up or down.", "Test choices with one or two points."],
  "trap": "Misreading the scale of the axes."},
"nlf-transform": {"name": "Shifts of a graph", "spot": "“shifted up 3 units”, “translated to the right”.",
  "steps": ["Up k: add k to the whole function. Down: subtract.", "Right h: replace x with (x − h). Left: (x + h)."],
  "trap": "Right shifts use a minus sign inside the bracket."},
"nlf-geom": {"name": "Area or volume as a function", "spot": "A rectangle or box whose length is written in terms of its width.",
  "steps": ["Write the area or volume formula with the expressions.", "Multiply out, or set equal to the given value and solve.", "Keep the positive length."],
  "trap": "Keeping a negative width."},
# ---- rat
"rat-convert": {"name": "Unit conversion", "spot": "“How many inches…”, “in feet per second”, “What is the depth in feet?”",
  "steps": ["Write the conversion as a fraction equal to 1 (12 inches / 1 foot).", "Arrange it so the old unit cancels.", "Chain several if needed."],
  "trap": "Multiplying when you should divide. Units that do not cancel show the mistake."},
"rat-square": {"name": "Square or cubic units", "spot": "An area in square feet to square yards; a volume in cubic units.",
  "steps": ["Square the length conversion for areas (1 yd² = 9 ft²).", "Cube it for volumes (1 ft³ = 1,728 in³)."],
  "trap": "Using the plain length conversion (3 instead of 9)."},
"rat-ratio": {"name": "Ratios and proportions", "spot": "“The ratio of a to b is 3 to 5…”, “proportional relationship”.",
  "steps": ["Write the ratio as a fraction.", "Set it equal to the second fraction with the same order.", "Cross-multiply."],
  "trap": "Flipping one ratio but not the other."},
"rat-rate": {"name": "Speed and other rates", "spot": "“at a constant speed of…”, “per hour”, “at this rate”.",
  "steps": ["distance = rate × time (and the same shape for any rate).", "Make the time units match before you multiply."],
  "trap": "Minutes and hours mixed."},
"rat-density": {"name": "Density", "spot": "“density”, “population density”.",
  "steps": ["density = amount ÷ space (mass ÷ volume, people ÷ area).", "Rearrange for what is missing.", "Find the volume or area first if a shape is described."],
  "trap": "Using a side length where the volume belongs."},
"rat-other": {"name": "Rates written as expressions", "spot": "A proportion written with letters: “Which expression gives the amount for…?”",
  "steps": ["Find the amount for 1 unit first.", "Multiply by the number of units asked for."],
  "trap": "Dividing in the wrong direction."},
# ---- pct
"pct-of": {"name": "Percent of a number", "spot": "“What is 30% of 80?”, “What percent of … is …?”, “How many of the items…”",
  "steps": ["Translate: is → =, of → ×, percent → ÷ 100.", "Solve the equation.", "Check the answer is sensible (part smaller than whole if under 100%)."],
  "trap": "Finding the percentage when the question asked for the count, or the reverse."},
"pct-change": {"name": "Percent increase and decrease", "spot": "“increased by”, “greater than”, “discount”, “net change”, “p% more than”.",
  "steps": ["Change: multiply by (1 + p/100) or (1 − p/100).", "Percent change = (new − old) ÷ old.", "Several changes: multiply the multipliers.", "Find the original: divide by the multiplier."],
  "trap": "Dividing by the new value; adding percents across several changes."},
# ---- 1vd
"1vd-mean": {"name": "Mean (average)", "spot": "“What is the mean…?”, “average”.",
  "steps": ["Mean = total ÷ count.", "From a frequency table: multiply each value by its frequency, add, divide by the total frequency.", "Missing value: total needed − total you have."],
  "trap": "Dividing by the number of rows in a frequency table instead of the total frequency."},
"1vd-median": {"name": "Median", "spot": "“What is the median…?”",
  "steps": ["Put the values in order.", "Middle position: (n + 1) ÷ 2. With an even count, average the middle two.", "In a frequency table, count up through the frequencies."],
  "trap": "Answering with a frequency instead of a value."},
"1vd-spread": {"name": "Range and standard deviation", "spot": "“range”, “standard deviation”, “spread”.",
  "steps": ["Range = largest − smallest.", "Standard deviation: compare only. More bunched around the middle = smaller."],
  "trap": "Thinking adding the same number to every value changes the spread."},
"1vd-change": {"name": "What happens when a value is added or removed", "spot": "“If the highest score is removed…”, “A sixth value is added…”",
  "steps": ["Work with totals: mean × count = total.", "Removing an extreme value moves the mean a lot and the median a little.", "Adding a value equal to the mean leaves the mean unchanged."],
  "trap": "Averaging two means without weighting them by count."},
"1vd-read": {"name": "Read a chart, dot plot or box plot", "spot": "Bar charts, dot plots, box plots and frequency tables.",
  "steps": ["Read the axis labels first.", "Box plot: the box spans the middle half; the line inside is the median; the ends are the minimum and maximum.", "Count carefully; answer what was asked."],
  "trap": "Reading the wrong bar or the wrong axis."},
# ---- 2vd
"2vd-predict": {"name": "Predict from the line of best fit", "spot": "“predicted by the line of best fit”, “closest to the estimated…”",
  "steps": ["Find the x-value on the bottom axis.", "Go up to the LINE, not to a dot.", "Read across to the y-axis, or put x into the line’s equation."],
  "trap": "Reading a nearby dot."},
"2vd-model": {"name": "Choose the best model", "spot": "“Which equation is the most appropriate model?”, “What type of function best models…?”",
  "steps": ["Rising or falling? That fixes the sign of the slope.", "Where does the trend cross the y-axis? That fixes b.", "Straight trend: linear. Curving faster and faster: exponential."],
  "trap": "A choice with the right slope but the wrong starting value."},
"2vd-slope": {"name": "Meaning of the slope", "spot": "“best interpretation of the slope of the line of best fit”.",
  "steps": ["Slope = predicted change in y for each 1-unit increase in x.", "Use the axis units in your sentence."],
  "trap": "A choice that says “actual” instead of “predicted”, or swaps x and y."},
"2vd-rate": {"name": "Average rate of change", "spot": "“average rate of change from … to …”, “greatest increase”.",
  "steps": ["Change in y ÷ change in x between the two points.", "Steeper segment = faster change."],
  "trap": "Dividing the wrong way round."},
"2vd-read": {"name": "Read the scatterplot or graph", "spot": "“How many…”, “Which of the following is true about…” a plotted data set.",
  "steps": ["Read the axes and scale.", "Find the exact data point or count the points asked about."],
  "trap": "Off by one grid line."},
# ---- prb
"prb-given": {"name": "Probability from a table (with a condition)", "spot": "Two-way tables; “given that”, “of those who”, “if a … is selected at random from…”",
  "steps": ["Identify the group named: that total is the bottom.", "The top is the cell inside that group with the feature asked.", "Give the form asked: fraction, decimal, percent."],
  "trap": "Using the grand total as the bottom."},
"prb-simple": {"name": "Simple probability", "spot": "One group, one feature: “what is the probability of selecting…”",
  "steps": ["Wanted ÷ total.", "Expected count = probability × total."],
  "trap": "Answering the opposite event (not defective instead of defective)."},
# ---- inf
"inf-moe": {"name": "Margin of error", "spot": "“with an associated margin of error of…”, “plausible”, “most appropriate conclusion”.",
  "steps": ["Range = estimate ± margin.", "The conclusion must be about the population sampled, and use the range.", "Bigger random sample → smaller margin."],
  "trap": "Treating the estimate as exact."},
"inf-estimate": {"name": "Scale a sample up to the population", "spot": "“Based on the sample, what is the best estimate of the number of … in the city?”",
  "steps": ["Sample share = count in sample ÷ sample size.", "Estimate = share × population size."],
  "trap": "Using the wrong population total."},
# ---- stc
"stc-general": {"name": "Who do the results apply to?", "spot": "“What is the largest population to which the results can be generalized?”",
  "steps": ["Find the group the sample was randomly chosen from.", "That group, no bigger, is the answer."],
  "trap": "A bigger group than the one sampled."},
"stc-design": {"name": "Is the study or survey sound?", "spot": "“Which of the following is true about the survey?”, “Which inference is appropriate?”",
  "steps": ["Random selection? Then you may generalize to that population.", "Random assignment? Then you may claim cause.", "Volunteers or one special location: biased."],
  "trap": "Claiming cause without random assignment."},
# ---- av
"av-area": {"name": "Area of flat shapes", "spot": "Rectangles, triangles, squares, circles: “What is the area…?”, or the area is given.",
  "steps": ["Formula from the reference sheet.", "Put in what you know.", "Solve for what is missing."],
  "trap": "Triangle area without the ½; diameter used as radius."},
"av-perimeter": {"name": "Perimeter", "spot": "“perimeter”: the distance around.",
  "steps": ["Add all the sides.", "Use the equal sides of squares and equilateral triangles."],
  "trap": "Confusing perimeter with area."},
"av-volume": {"name": "Volume of solids", "spot": "Cylinders, cones, spheres, prisms, pyramids: volume given or asked.",
  "steps": ["Formula from the reference sheet (cone and pyramid have 1/3).", "Put in everything known.", "Solve for the missing length if the volume is given."],
  "trap": "Dropping the 1/3, or using the diameter."},
"av-surface": {"name": "Surface area", "spot": "“surface area” of a box or prism.",
  "steps": ["Sketch the faces: a box has 3 pairs of matching rectangles.", "Add the area of every face. Leave out any face the question removes (no lid)."],
  "trap": "Giving the volume, or counting a missing lid."},
"av-scale": {"name": "Scaling a shape", "spot": "“each side is 3 times…”, “the length and width are increased by…”, similar shapes.",
  "steps": ["Lengths × k → areas × k², volumes × k³.", "A percent increase in each length: multiply area by (1 + p/100)²."],
  "trap": "Scaling an area by k instead of k²."},
# ---- lat
"lat-parallel": {"name": "Parallel lines and a transversal", "spot": "“Line ℓ is parallel to line m…”",
  "steps": ["Angles in the same position at each crossing are equal.", "Z-shaped (alternate) angles are equal.", "Same-side inside angles add to 180°."],
  "trap": "Setting two angles equal when they actually add to 180°."},
"lat-lines": {"name": "Intersecting lines", "spot": "“Two lines intersect at a point…”, vertical angles, a line extended.",
  "steps": ["Opposite (vertical) angles are equal.", "Angles on a straight line add to 180°."],
  "trap": "Treating neighbouring angles as equal."},
"lat-triangle": {"name": "Angles in triangles and polygons", "spot": "Triangle angle measures, isosceles or equilateral triangles, exterior angles, polygons.",
  "steps": ["Triangle angles add to 180°.", "Isosceles: the angles opposite the equal sides are equal.", "Exterior angle = the two far inside angles added.", "Polygon angle total = 180(n − 2)."],
  "trap": "Forgetting that the base angles of an isosceles triangle are equal."},
"lat-similar": {"name": "Similar and congruent triangles", "spot": "“similar”, “congruent”, “corresponds to”, “dilated by a scale factor”.",
  "steps": ["Match corresponding vertices from the order of the letters.", "Scale factor = matching side ÷ matching side.", "Angles stay the same; lengths multiply by the scale factor."],
  "trap": "Matching sides that are not in corresponding positions."},
# ---- rtt
"rtt-pythag": {"name": "Pythagorean theorem", "spot": "A right triangle with two sides known; “hypotenuse”, “diagonal”.",
  "steps": ["Look for a known triple (3-4-5, 5-12-13) and its multiples.", "Otherwise a² + b² = c², with c across from the right angle.", "Leave the answer as a root if the choices do."],
  "trap": "Adding the squares when the missing side is a leg (subtract instead)."},
"rtt-trig": {"name": "Sine, cosine and tangent", "spot": "“sin”, “cos”, “tan” of an angle in a right triangle.",
  "steps": ["Label opposite, adjacent and hypotenuse from the named angle.", "SOH: sin = opp/hyp. CAH: cos = adj/hyp. TOA: tan = opp/adj.", "Missing side? Use the triple or Pythagoras first."],
  "trap": "Labelling the sides from the wrong angle."},
"rtt-complement": {"name": "sin of one angle = cos of the other", "spot": "Two acute angles that add to 90°; sin given, cos asked (or the reverse).",
  "steps": ["sin(x°) = cos(90° − x°).", "If sin A = cos B, then A + B = 90°."],
  "trap": "Calculating when the answer is the number you were given."},
"rtt-special": {"name": "30-60-90 and 45-45-90 triangles", "spot": "Angles of 30°, 45° or 60°; isosceles right triangles; equilateral triangles; squares.",
  "steps": ["45-45-90: legs x, x; hypotenuse x√2.", "30-60-90: short side x, long side x√3, hypotenuse 2x.", "Cut an equilateral triangle in half to get two 30-60-90 triangles."],
  "trap": "Putting √3 on the wrong side."},
"rtt-similar": {"name": "Similar right triangles", "spot": "A right triangle with a parallel line or a second triangle inside it.",
  "steps": ["Equal angles mean similar triangles.", "Set up matching sides in proportion, or use equal trig ratios."],
  "trap": "Matching sides by position on the page instead of by angle."},
# ---- cir
"cir-read": {"name": "Center and radius from the equation", "spot": "“What is the radius / center of the circle with equation …?”",
  "steps": ["(x − h)² + (y − k)² = r²: center (h, k), radius √(right side).", "Multiplied-out equation: complete the square for x and for y.", "Diameter = 2 × radius."],
  "trap": "r² given as the radius; center signs reversed.",
  "desmos": "Desmos draws the circle but does not label its center. Read the center and radius from the grid, which works only when they are whole numbers."},
"cir-build": {"name": "Write the circle’s equation", "spot": "“Which equation represents a circle with center … and radius …?”",
  "steps": ["Write (x − h)² + (y − k)² = r².", "Square the radius.", "If a point on the circle is given, the radius is its distance from the center."],
  "trap": "Writing r instead of r² on the right side."},
"cir-transform": {"name": "Shifted or resized circles", "spot": "“Circle B is circle A shifted down 3”, “same center, twice the radius”.",
  "steps": ["Read circle A’s center and radius.", "Shift the center; scale the radius.", "Write the new equation, squaring the new radius."],
  "trap": "Doubling r² instead of r (twice the radius makes r² four times as big)."},
"cir-radians": {"name": "Radians and degrees", "spot": "“radians”, “degrees”, the unit circle.",
  "steps": ["180° = π radians.", "Degrees to radians: × π/180. Radians to degrees: × 180/π.", "On the unit circle, a point at angle θ is (cos θ, sin θ)."],
  "trap": "Multiplying by the wrong fraction."},
"cir-arc": {"name": "Arcs, sectors and circumference", "spot": "“arc”, “sector”, “central angle”, “circumference”.",
  "steps": ["Arc length = (angle ÷ 360) × 2πr.", "Sector area = (angle ÷ 360) × πr².", "In radians: arc length = r × angle."],
  "trap": "Using the area formula for an arc length."},
"cir-tangent": {"name": "Tangent lines", "spot": "“tangent to the circle at the point…”",
  "steps": ["The radius to the touching point is perpendicular to the tangent.", "Tangent slope = negative reciprocal of the radius’s slope."],
  "trap": "Using the radius’s slope as the tangent’s slope."},
"cir-geo": {"name": "Circle figures", "spot": "A figure with a circle, radii and a triangle; “What is the value of x?”",
  "steps": ["All radii are equal, so triangles from the center are isosceles.", "Use triangle angle sums and any right angles at tangent points."],
  "trap": "Assuming the figure is drawn to scale when it says it is not."},
}
