# Big patterns, rare patterns and the Desmos playbook. Counts are filled in by mbuild.py from mpatterns.py.
# Every "proof" question id below was solved with the method shown and matched College Board's answer (verified.json).

DESMOS = [
 {"id": "both", "name": "Graph both sides", "short": "Any equation with one unknown",
  "when": "Any equation with one unknown: linear, quadratic, square roots, fractions, exponents. Also “at what time does … reach …?”",
  "type": ["y = (left side)", "y = (right side)"],
  "see": "Click where the two graphs cross. The x-value of each crossing is a solution.",
  "why": "Solving an equation means finding where the two sides are equal, which is where their graphs meet. Desmos graphs a square root only where it is real and non-negative, so false (extraneous) answers never show up.",
  "watch": "If the unknown is not called x, rename it x first. If the crossing is off the screen, press the zoom-to-fit (magnifier) button.",
  "proof": ["66bce0c1", "722de804", "f67e4efc", "301faf80", "ae05d37b"]},
 {"id": "zero", "name": "Zero it out", "short": "How many solutions? Sum of solutions?",
  "when": "“How many solutions does the equation have?”, “What is the sum of the solutions?”, or when one side is already 0.",
  "type": ["y = (left side) − (right side)"],
  "see": "Every x-intercept (gray dot on the x-axis) is a solution. Count them, or add them.",
  "why": "left = right is the same as left − right = 0, and a graph equals 0 where it crosses the x-axis.",
  "watch": "A graph that only touches the axis is one solution, not two.",
  "proof": ["722de804", "91e7ea5e"]},
 {"id": "twolines", "name": "Two facts, two lines", "short": "Word problems with two unknowns",
  "when": "Two unknown amounts and two facts about them: tickets, tents, mixtures, alloys, coins, a total count and a total cost.",
  "type": ["x + y = (total count)", "(price or %)·x + (price or %)·y = (total value)"],
  "see": "Click the crossing point (x, y). Then answer exactly what was asked (it may be 12x, 0.8y, or x + y).",
  "why": "Each fact is a line. The only pair that makes both facts true is where the lines cross.",
  "watch": "Let x and y stand for the two amounts and write down which is which. Mixture questions: amount of salt = percent × amount of solution.",
  "proof": ["7866a908", "d7bf55e1", "71189542", "a1fd2304", "107d0c62"]},
 {"id": "list", "name": "Test all four choices at once", "short": "Number choices",
  "when": "Multiple choice with number choices: “What is a solution?”, “Which could be the value of …?”",
  "type": ["L = [choice A, choice B, choice C, choice D]", "(left side with L in place of x) − (right side with L)"],
  "see": "Desmos shows a list of four results. The choice that gives 0 (or makes a statement true) is the answer.",
  "why": "Desmos does arithmetic on whole lists at once, so one line backsolves all four choices.",
  "watch": "Type square roots as sqrt( ). Choices with π or fractions can be typed exactly.",
  "proof": ["ba0edc30", "6ce95fc8", "d8789a4c"]},
 {"id": "chain", "name": "Chain it", "short": "Percents of percents, unit chains",
  "when": "Several linked facts: “a is 30% greater than b, b is 20% less than c…”, conversions in a chain, growth then decline.",
  "type": ["c = 100", "b = 0.8c", "a = 1.3b", "a/c"],
  "see": "Desmos shows the value of each line. The last line is the answer (for a percent, ×100).",
  "why": "Every percent, rate and conversion is a multiplication. Writing one line per sentence keeps each multiplier where it belongs, and Desmos accepts the lines in any order.",
  "watch": "“p% greater than” is ×(1 + p/100). “p% less than” is ×(1 − p/100). “p% of” is ×p/100. When no number is given, set the free letter to 100.",
  "proof": ["4aaa9c42", "993000da", "1fbd3b67", "58ba7239", "a51e6f93", "25faa756"]},
 {"id": "slide", "name": "Slide the constant", "short": "Find the constant (k, a, b…)",
  "when": "A constant you have to find: the graph must pass through a point, touch a line, have no solution, or have one solution.",
  "type": ["Type the equations exactly as given, with the constant as a letter.", "Click “add slider” for the letter."],
  "see": "Drag the slider until the picture matches the condition: lines parallel (no solution), the same line (infinitely many), a curve just touching (exactly one).",
  "why": "A constant is just a number you have not been told yet. The slider lets you watch what each value does.",
  "watch": "Sliders move in steps of 0.1. When the answer is an awkward fraction, use the next move instead.",
  "proof": ["ff501705", "fc3d783a"]},
 {"id": "swapx", "name": "Turn the constant into x", "short": "Exact constants, integer limits",
  "when": "You know the condition: equal slopes, equal coefficients, or b² − 4ac = 0 (one solution), < 0 (none), > 0 (two).",
  "type": ["Write the condition as an equation, using x in place of the constant.", "e.g. y = (x − 2)² − 4(1)(55) for “no real solutions”"],
  "see": "The x-intercepts are the boundary values of the constant. For “greatest integer”, step just inside the boundary.",
  "why": "Once the condition is an equation in the constant, finding the constant is just solving it.",
  "watch": "At the boundary itself the discriminant is 0 (one solution). “No solution” needs the integer strictly inside.",
  "proof": ["e6cb2402", "46308566", "1fe32f7d"]},
 {"id": "fit", "name": "Fit it (regression)", "short": "“True for all x” constants, tables",
  "when": "“equivalent to … where a, b, c are constants”, “true for all x”, a table of values, two points on a line, an exponential table.",
  "type": ["x_1 = [1, 2, 3, 4, 5]", "y_1 = (the side you know, with x_1 in place of x)", "y_1 ~ (the side with the unknown constants, using x_1)"],
  "see": "Desmos lists the constants (a = …, b = …). R² = 1 means a perfect match.",
  "why": "Two expressions that are equal for every x are equal at x = 1, 2, 3, 4, 5. The ~ sign makes Desmos find the constants that make every point match.",
  "watch": "Type the subscript with an underscore: x_1. Use at least as many x-values as there are unknown constants. For a table, type its columns into x_1 and y_1.",
  "proof": ["371cbf6b", "38c90632", "b4a6ed81", "ea6d05bb", "e9908930", "58c7daed"]},
 {"id": "dots", "name": "Click the gray dots", "short": "Vertex, zeros, intercepts",
  "when": "Maximum, minimum, vertex, zeros, x- and y-intercepts, where two curves meet.",
  "type": ["y = (the function)"],
  "see": "Click the curve. Gray dots appear at the vertex, the intercepts and any crossings; click one to read its coordinates.",
  "why": "Desmos finds these special points for you, so a hard algebra step becomes a read.",
  "watch": "The vertex gives two numbers: the maximum or minimum VALUE is the y-coordinate; WHERE it happens is the x-coordinate. Large numbers? Press zoom-to-fit.",
  "proof": ["358f18bc", "8e1da169", "91e7ea5e"]},
 {"id": "legal", "name": "Make up legal numbers", "short": "Constants known only by conditions",
  "when": "Constants are given only by conditions (“a > 7”, “0 < a < b”, “positive constants”) and the question asks what must be true, how many times a graph crosses, or which graph it could be.",
  "type": ["Pick values that obey every condition, e.g. a = 8, b = 2, c = 1", "Type the equation with those values"],
  "see": "Read the answer from the picture. Try a second set of legal values to make sure it does not change.",
  "why": "If something is true for every allowed value, it is true for the values you picked.",
  "watch": "Obey every condition exactly. Avoid 0 and 1 unless the conditions force them.",
  "proof": ["f01108a8", "2c05d312", "0b46bad5", "4e18fc5d"]},
 {"id": "circle", "name": "Vertex trick for circles", "short": "Center and radius of a messy circle",
  "when": "A circle given as x² + y² + Dx + Ey = F (multiplied out).",
  "type": ["y = x² + Dx", "y = x² + Ey"],
  "see": "The x-coordinate of each vertex is the center: h from the first, k from the second. Each vertex’s y-value, made positive, is the number to add to the right side to get r².",
  "why": "x² + Dx has its vertex at x = −D/2 and y = −(D/2)², exactly the numbers completing the square needs. Desmos draws the circle but does not mark its center, so this trick fills the gap.",
  "watch": "The right side is r², so take the square root at the end.",
  "proof": ["2266984b", "76c73dbf"]},
 {"id": "stats", "name": "Lists for statistics", "short": "Mean, median, spread, missing values",
  "when": "Mean, median, range, standard deviation, a missing value, an integer that must make a mean work.",
  "type": ["L = [4, 10, 18, 4, 4, 5, 6, 5]", "mean(L)   median(L)   max(L) − min(L)   stdev(L)", "Frequency table: total(V·F)/total(F) for the mean"],
  "see": "Each function gives its value immediately.",
  "why": "Typing the data once avoids counting and sorting errors.",
  "watch": "For many possible values at once use a range list: X = [1...59], then (total(L) + X)/10 shows every possible mean.",
  "proof": ["a5b069b4", "190be2fc", "1e8ccffd"]},
 {"id": "shade", "name": "Shade and drop the points", "short": "Inequalities and regions",
  "when": "Systems of inequalities, “which point is a solution”, shaded regions.",
  "type": ["y ≤ x + 7", "y ≥ −2x − 1", "[(−14, 0), (0, −14), (0, 14), (14, 0)]"],
  "see": "The answer is the point inside the region where both shadings overlap.",
  "why": "Desmos shades each inequality and draws dashed or solid borders the way the test does.",
  "watch": "A point exactly on a dashed border is not a solution.",
  "proof": ["541bef2f"]},
 {"id": "machine", "name": "Function machine", "short": "f(3), f(x + 2), tables",
  "when": "Any question that names a function: f(3), f(x) = 10, which table matches, composite functions.",
  "type": ["f(x) = (the formula)", "f(3)", "y = f(x + 2)  or  y = 10 to find where f(x) = 10"],
  "see": "Desmos evaluates f(3) on the spot. Add a table to see many values.",
  "why": "Defining the function once prevents retyping mistakes.",
  "watch": "Use a letter other than x or y for any extra constant.",
  "proof": ["e9908930"]},
]

GOTCHAS = [
 ("x and y are taken", "Typing x = 2 draws a vertical line; it does not store 2. Give other unknowns other letters, or rename the question’s x to a."),
 ("Check the mode before trigonometry", "Wrench icon → Degrees when the question uses °. Radians when it uses π."),
 ("Off the screen", "Press zoom-to-fit (the magnifier) when a crossing or vertex is not visible, especially with large numbers."),
 ("Decimals, not fractions", "Desmos shows 1.16666…; compare with the choices in decimal form (7/6 = 1.1667)."),
 ("Subscripts", "Lists for regression need subscripts: type x_1 and y_1 with an underscore."),
 ("No gray dot?", "If clicking a graph shows no points, rewrite it as y = … so Desmos can find them."),
 ("Slider steps", "Sliders move in steps of 0.1 by default. Type an exact value into the slider, or turn the condition into an equation."),
 ("Two steps or fewer? Skip it", "Typing a short question into Desmos takes longer than doing it by hand."),
]

PATTERNS = [
 {"id": "plug", "name": "Plug it in", "idea": "A value, a point or an answer choice that makes a statement true can be put back into it.",
  "spot": "“passes through the point”, “f(3)”, “when x = …”, “which point / table…”, a constant with one known point.",
  "hand": "Replace each letter with its value, every place it appears, then work it out.",
  "desmos": ["machine", "list", "dots"],
  "proof": ["b8f13a3a", "e9908930", "4e18fc5d"],
  "check": "College Board’s own explanations use substitution in about a third of all math questions, more than any other step."},
 {"id": "cross", "name": "Equal means crossing", "example": {"q": "Solve √(x + 6) = x.", "desmos": ["y = sqrt(x + 6)", "y = x"], "result": "One crossing, at x = 3. Squaring by hand also gives x = −2, which is false; Desmos never shows it."},
  "idea": "Every equation is two graphs, and every solution is a place where they cross.",
  "spot": "“What is the solution…”, “the graphs intersect at…”, “when does … reach…”, systems.",
  "hand": "Get everything on one side, then factor, use the quadratic formula, or eliminate a variable.",
  "desmos": ["both", "zero", "twolines"],
  "proof": ["66bce0c1", "722de804", "f67e4efc", "301faf80"],
  "check": "This one idea solves linear equations, quadratics, square-root and fraction equations, exponentials and systems, which are five different skills in College Board’s list."},
 {"id": "constant", "name": "A constant plus one fact", "example": {"q": "The system 2x + 3y = 7 and kx + 6y = 9 has no solution. What is k?", "desmos": ["2x + 3y = 7", "kx + 6y = 9", "(add a slider for k)"], "result": "At k = 4 the lines are parallel and never meet. By hand: same slope means k/6 = 2/3."},
  "idea": "An unknown constant always comes with exactly one extra fact. Turn that fact into one equation in the constant.",
  "spot": "The word “constant”. It makes a question Hard more than any other word.",
  "hand": "Decide what kind of fact it is: a point on the graph (plug it in), “equivalent / for all x” (match coefficients), or a number of solutions (compare slopes, or b² − 4ac).",
  "desmos": ["slide", "swapx", "fit", "legal"],
  "proof": ["ff501705", "fc3d783a", "46308566", "b8f13a3a", "371cbf6b"],
  "check": "In the bank, questions with the word “constant” are Hard 69% of the time, against 32% for the bank as a whole. The fact is one of four kinds: a number of solutions, “equivalent / for all x”, a point on the graph, or a model."},
 {"id": "disguise", "name": "The same expression in disguise", "example": {"q": "(x + 3)² = x² + bx + c for all x. What are b and c?", "desmos": ["x_1 = [1, 2, 3, 4]", "y_1 = (x_1 + 3)^2", "y_1 ~ x_1^2 + b x_1 + c"], "result": "Desmos reports b = 6 and c = 9 with R² = 1."},
  "idea": "“Equivalent”, “true for all x” and “infinitely many solutions” all mean the two sides are the same expression written differently.",
  "spot": "“equivalent”, “for all values of x”, “infinitely many solutions”, “can be rewritten as”.",
  "hand": "Expand both sides and match the x², x and plain-number parts. Or put x = 2 into both sides.",
  "desmos": ["fit", "list"],
  "proof": ["371cbf6b", "38c90632", "ea6d05bb", "b4a6ed81"],
  "check": "Rewriting expressions questions use it every time, and it is also how “infinitely many solutions” is settled in one-variable equations and in systems."},
 {"id": "count", "name": "Counting solutions is counting crossings", "idea": "One crossing: one solution. Parallel lines or a curve that misses: none. The same line: infinitely many. A curve just touching a line: exactly one.",
  "spot": "“how many solutions”, “no solution”, “infinitely many”, “exactly one”, “how many times does the graph cross”.",
  "hand": "Lines: compare slopes, then intercepts. Quadratics: b² − 4ac positive (2), zero (1), negative (0).",
  "desmos": ["zero", "slide", "swapx", "legal"],
  "proof": ["ff501705", "e6cb2402", "f01108a8", "fc3d783a"],
  "check": "These questions are Hard far more often than average. They come in three kinds: two lines, one equation in x, and quadratics. The crossing picture covers all three."},
 {"id": "multiplier", "name": "Everything is a multiplier", "example": {"q": "a is 20% of b, b is 150% of c, and c is 40% of d. a is what percent of d?", "desmos": ["d = 100", "c = 0.4d", "b = 1.5c", "a = 0.2b"], "result": "Desmos shows a = 12, so a is 12% of d. By hand: 0.2 × 1.5 × 0.4 = 0.12."},
  "idea": "Percents, growth, decay, unit conversions and scale factors are all multiplication by a factor.",
  "spot": "percent, “increases by”, “each year”, “per”, “in feet”, “times as long”, “each side is doubled”.",
  "hand": "p% more: ×(1 + p/100). p% less: ×(1 − p/100). Several changes: multiply the factors. Areas scale by k², volumes by k³.",
  "desmos": ["chain"],
  "proof": ["4aaa9c42", "1fbd3b67", "58ba7239", "e53add44", "ae05d37b"],
  "check": "It links four skills: percentages, exponential functions, units and scaling in geometry. The chained-percent questions, almost all Hard, are just three multipliers in a row."},
 {"id": "rate", "name": "Rate means change ÷ change", "idea": "Slope, unit rate, speed, average rate of change and the slope of a line of best fit are the same number: how much y changes for each 1 that x changes.",
  "spot": "“slope”, “per”, “each additional”, “rate of change”, a table with evenly spaced x-values, a line of best fit.",
  "hand": "(y₂ − y₁) ÷ (x₂ − x₁). In a story, the rate follows the word “per” or “each”.",
  "desmos": ["fit", "dots"],
  "proof": ["58c7daed", "e9908930", "db422e7f", "1adb39f0"],
  "check": "It runs through linear functions, linear equations, scatterplots and rates: four skills, over a seventh of the bank."},
 {"id": "ratio", "name": "Same shape, same ratio", "idea": "Similar triangles, trig ratios, arcs, scale drawings and sample-to-population estimates all keep one ratio fixed.",
  "spot": "“similar”, “corresponds to”, sin/cos/tan, “arc”, “scale”, “based on the sample”.",
  "hand": "Write the matching parts as two equal fractions and cross-multiply. Or find the scale factor once and apply it.",
  "desmos": ["both"],
  "proof": ["bd87bc09"],
  "check": "College Board’s explanations call on a proportion in triangles, circles, rates, probability and sampling."},
 {"id": "twofacts", "name": "Two unknowns need two facts", "example": {"q": "A chemist mixes a 10% sodium nitrate solution with a 40% sodium nitrate solution to make 60 liters of a 20% solution. How many liters of the 10% solution are used?", "desmos": ["x + y = 60", "0.10x + 0.40y = 0.20(60)"], "result": "The lines cross at (40, 20): 40 liters of the 10% solution and 20 liters of the 40% solution."},
  "idea": "When a story has two unknown amounts, it always gives two facts about them, usually a total count and a total value.",
  "spot": "Two kinds of ticket, tent, coin or solution; “a total of … for …”; mixtures “x% by mass”.",
  "hand": "Write one equation per fact, then eliminate one letter.",
  "desmos": ["twolines"],
  "proof": ["7866a908", "d7bf55e1", "71189542", "a1fd2304", "107d0c62"],
  "check": "Mostly Easy and Medium, but the answer is often a third quantity (the silicon in the second piece, the money spent on adults), and that third quantity is the trap."},
 {"id": "form", "name": "The form shows the answer", "idea": "Each standard form has its key facts printed in it: y = mx + b, a(x − h)² + k, a(x − p)(x − q), (x − h)² + (y − k)² = r², a·bˣ.",
  "spot": "Vertex, zeros, intercepts, starting amount, growth rate, center, radius: “which equation displays …”.",
  "hand": "Read the number from the right place; watch the signs inside brackets.",
  "desmos": ["dots", "circle"],
  "proof": ["91e7ea5e", "8e1da169", "2266984b", "e53add44"],
  "check": "Nonlinear functions, circles and linear equations all have “read it off the form” questions, and the hard ones ask which form displays a value."},
 {"id": "symmetry", "name": "A parabola is symmetric", "idea": "The vertex sits exactly halfway between the two zeros, so the sum of the solutions is twice the vertex’s x: −b/a.",
  "spot": "maximum, minimum, vertex, “sum of the solutions”, “highest point”.",
  "hand": "Vertex x = average of the zeros = −b/(2a). Sum of solutions = −b/a, product = c/a.",
  "desmos": ["dots", "zero"],
  "proof": ["8e1da169", "722de804", "358f18bc", "2c05d312"],
  "check": "Maximum-and-minimum and sum-of-solutions questions are among the most often Hard in the bank, and symmetry settles both."},
 {"id": "whole", "name": "Divide by the right whole", "idea": "Probability, “percent of”, means and percent change are all part ÷ whole. The work is choosing the whole.",
  "spot": "“given that”, “of those who”, “what percent of”, “mean”, “percent increase”.",
  "hand": "Underline the group the question names; that total goes on the bottom. Percent change divides by the OLD value. Mean × count = total.",
  "desmos": ["stats"],
  "proof": ["1e8ccffd", "190be2fc", "a5b069b4", "0231050d"],
  "check": "It covers percentages, one-variable data, probability and inference from samples."},
 {"id": "pythag", "name": "Pythagoras is everywhere", "idea": "a² + b² = c² governs right triangles, special triangles, distances and the circle equation itself.",
  "spot": "right triangle, hypotenuse, diagonal, sin/cos given as a fraction, circle equation, distance between points.",
  "hand": "Look for 3-4-5 and 5-12-13 first. The circle equation is Pythagoras: horizontal gap² + vertical gap² = r².",
  "desmos": ["circle", "both"],
  "proof": ["bd87bc09", "76c73dbf", "2266984b"],
  "check": "It is the hidden step in most right-triangle and circle questions, and those two skills are each about 60% Hard."},
]

RARE = [
 {"name": "Chained percents", "key": "chained percents", "trick": "One line per sentence in Desmos with the free number set to 100, or multiply the factors: 30% more then 20% less is 1.3 × 0.8 = 1.04.", "proof": ["4aaa9c42", "58ba7239"], "desmos": "chain"},
 {"name": "Sum or product of the solutions", "key": "sum/product of solutions", "trick": "Sum = −b/a, product = c/a. No solving.", "proof": ["722de804", "2c05d312"], "desmos": "zero"},
 {"name": "Integer limits (“greatest integer”, “positive integer”)", "key": "integer conditions (test a list)", "trick": "Find the boundary, then step to the nearest allowed integer. Or list every candidate: X = [1...60].", "proof": ["46308566", "1fe32f7d", "190be2fc"], "desmos": "swapx"},
 {"name": "Square-root equations", "key": "extraneous (square both sides)", "trick": "Square, solve, then check each answer in the original. In Desmos the false answer never appears.", "proof": ["66bce0c1"], "desmos": "both"},
 {"name": "Shifted graphs", "key": "shifted graphs", "trick": "Up k: add k outside. Right h: replace x with (x − h). Circles: move the center, keep the radius.", "proof": [], "desmos": "machine"},
 {"name": "Doubling time and half-life", "key": "doubling / half-life time", "trick": "In a·2^(t/n) the doubling time is n. In Desmos, cross the curve with y = 2a. These are never Hard in the bank.", "proof": ["ae05d37b"], "desmos": "both"},
 {"name": "Radians and degrees", "key": "radians and degrees", "trick": "180° = π radians. Multiply by π/180 or by 180/π.", "proof": [], "desmos": None},
 {"name": "sin x° = cos(90° − x°)", "key": "sin x = cos(90-x)", "trick": "If the angles add to 90°, the sine of one is the cosine of the other.", "proof": [], "desmos": None},
 {"name": "Surface area", "key": "surface area", "trick": "Add the area of every face; a box has three matching pairs. Leave out any face that is missing.", "proof": [], "desmos": None},
 {"name": "Messy circle equations", "key": "expanded circle equation (vertex trick)", "trick": "Complete the square, or use the Desmos vertex trick.", "proof": ["2266984b", "76c73dbf"], "desmos": "circle"},
 {"name": "Mixtures and concentrations", "key": "mixtures and concentrations", "trick": "Amount of substance = percent × amount of mixture, and both the totals and the substance amounts add up.", "proof": ["7866a908", "a1fd2304"], "desmos": "twolines"},
 {"name": "Constants known only by conditions", "key": "constants known only by conditions (made-up numbers)", "trick": "Pick values that obey the conditions and look at the result; try a second set.", "proof": ["f01108a8", "0b46bad5"], "desmos": "legal"},
 {"name": "Tangent lines to circles", "key": "tangent ⟂ radius", "trick": "The radius to the touching point is perpendicular to the tangent: its slope is the negative reciprocal.", "proof": [], "desmos": None},
 {"name": "Who the results apply to", "key": "study design / generalizing", "trick": "Only to the group that was randomly sampled; cause and effect only with random assignment.", "proof": [], "desmos": None},
]

# Desmos line for every question type: (move id or None, text)
TYPE_DESMOS = {
 "le1-solve": ("both", "Type y = left side and y = right side; click the crossing. Faster by hand when it is two steps."),
 "le1-count": ("slide", "Graph y = left and y = right: parallel lines mean no solution, the same line means infinitely many. With a constant, slide it."),
 "le1-model": ("list", "Not needed to choose the equation. To check it, put the story’s numbers into each choice."),
 "le1-word": ("both", "Usually quicker by hand. For an awkward one, graph both sides of your equation."),
 "lf-eval": ("machine", "f(x) = formula, then type f(3). For f(x) = 10, add y = 10 and click the crossing."),
 "lf-model": ("fit", "Put two (x, total) pairs from the story into a table and fit y_1 ~ m x_1 + b."),
 "lf-interpret": (None, "Not needed: match the number’s units (per x → slope; starting value → y-intercept)."),
 "lf-intercept": ("dots", "Graph it and click the intercepts."),
 "lf-table": ("fit", "Type the table into x_1 and y_1, then y_1 ~ m x_1 + b gives the slope and intercept."),
 "lf-graph": (None, "Read two exact points from the picture; Desmos is not needed."),
 "lf-build": ("fit", "Put the two points in a table and fit y_1 ~ m x_1 + b."),
 "le2-parallel": ("dots", "Graph the given line and click two points to get the slope, then flip and change the sign."),
 "le2-model": (None, "Build it from the story; Desmos does not help choose."),
 "le2-interpret": (None, "Match the units; Desmos is not needed."),
 "le2-intercept": ("dots", "Graph the equation as written and click where it crosses the axes."),
 "le2-point": ("machine", "Graph the line and plot the point or the table rows; they must sit on the line."),
 "le2-solve": ("both", "Put in the known value and graph both sides, or solve by hand in one step."),
 "sys-solve": ("twolines", "Type both equations exactly as given and click the crossing point."),
 "sys-count": ("slide", "Graph both lines with the constant on a slider: parallel = no solution, same line = infinitely many."),
 "sys-model": ("twolines", "Not needed to choose. To check, graph your system: the crossing should match the story."),
 "sys-graph": ("twolines", "If the equations are given, type them and click the crossing."),
 "sys-word": ("twolines", "Write the count fact and the value fact with x and y, type both, click the crossing, then answer what was asked."),
 "inq-model": ("shade", "Type each choice as an inequality and plot a point the story allows."),
 "inq-maxmin": ("both", "Graph the cost or total line and the limit line; read the crossing, then round the way the story allows."),
 "inq-point": ("shade", "Type the inequality and drop the choices as a list of points."),
 "inq-graph": ("shade", "Type each choice; the one whose shading matches the picture is the answer."),
 "eqx-rewrite": ("fit", "Graph the original and each choice as y = …; the choice whose graph lies exactly on top is equivalent."),
 "eqx-coef": ("fit", "x_1 = [1,2,3,4,5]; y_1 = known side; y_1 ~ side with the constants. Desmos reports them."),
 "eqx-exp": ("list", "Define f(x) = original and g(x) = each choice; compare f(2) and g(2) (and f(3), g(3))."),
 "eqx-rational": ("fit", "Regression with x_1 = [1,2,3,4,5] finds the constants in the rewritten form."),
 "nle-solve": ("both", "Graph both sides and click the crossings. With number choices, test them all as a list."),
 "nle-sign": ("both", "Graph both sides; keep the crossing with the sign the question allows."),
 "nle-literal": ("legal", "Rename x if it appears; give each other letter an easy value, then check which choice returns the right number."),
 "nle-count": ("zero", "Graph y = left − right and count the x-intercepts. With a constant, turn the discriminant into a graph in the constant."),
 "nle-sum": ("zero", "Click both zeros and add them, or double the vertex’s x. By hand: −b/a."),
 "nle-system": ("both", "Type both equations and click every crossing."),
 "nle-radical": ("both", "Graph both sides: only the real solutions appear, so false answers are filtered out for you."),
 "nlf-eval": ("machine", "Define f(x) and type f(3), or graph y = f(x) and y = k for “f(x) = k”."),
 "nlf-vertex": ("dots", "Graph it and click the turning point. Value = y-coordinate; where = x-coordinate."),
 "nlf-exp": ("fit", "From a table: y_1 ~ a·b^(x_1). From words: check a choice by graphing it."),
 "nlf-exp-int": (None, "Read the base: above 1 grows by (b − 1)×100%, below 1 shrinks by (1 − b)×100%."),
 "nlf-height": ("dots", "Graph the height; the vertex is the highest point and the positive x-intercept is when it lands."),
 "nlf-interpret": (None, "Work out what the expression stands for in the story; Desmos is not needed."),
 "nlf-zeros": ("dots", "Graph it and click the x-intercepts."),
 "nlf-yint": ("slide", "Graph with the constants on sliders and adjust until the graph passes through the given point, or put the point in by hand."),
 "nlf-graph": ("machine", "Type the function or each choice and compare with the picture or the table."),
 "nlf-transform": ("machine", "Graph f(x) and each choice; the shifted one lands exactly on the target."),
 "nlf-geom": ("both", "Graph the area or volume formula as y = … and y = the given value; click the crossing."),
 "rat-convert": ("chain", "One line per conversion factor, or just multiply on the calculator; units are not checked by Desmos."),
 "rat-square": ("chain", "Square (or cube) the conversion factor before multiplying."),
 "rat-ratio": ("both", "Write the proportion with x as the unknown and graph both sides."),
 "rat-rate": (None, "Use it as a calculator; set the units first."),
 "rat-density": ("chain", "Define volume first, then mass = density × volume, line by line."),
 "rat-other": ("chain", "Find the amount for one unit on one line, then multiply."),
 "pct-of": ("chain", "Type the percent as a decimal times the number; for “what percent”, divide and ×100."),
 "pct-change": ("chain", "One line per change: start = 100, then ×1.2, ×0.8 …; or (new − old)/old × 100."),
 "1vd-mean": ("stats", "L = [the data], then mean(L). Frequency table: total(V·F)/total(F)."),
 "1vd-median": ("stats", "L = [the data], then median(L)."),
 "1vd-spread": ("stats", "max(L) − min(L) for the range; stdev(L) only to compare two sets."),
 "1vd-change": ("stats", "Type the data before and after the change and compare mean(…) and median(…)."),
 "1vd-read": (None, "Read the chart carefully; Desmos is not needed."),
 "2vd-predict": ("machine", "If the line’s equation is given, define f(x) and type f(8)."),
 "2vd-model": ("fit", "Type a few points from the plot into x_1, y_1 and fit y_1 ~ m x_1 + b or y_1 ~ a·b^(x_1)."),
 "2vd-slope": (None, "Not needed: say the slope as “y changes by m for each 1 that x increases”."),
 "2vd-rate": ("fit", "Two points in a table, then y_1 ~ m x_1 + b; m is the average rate of change."),
 "2vd-read": (None, "Read the graph; Desmos is not needed."),
 "prb-given": (None, "Use it only as a calculator: right cell ÷ right total."),
 "prb-simple": (None, "Use it only as a calculator."),
 "inf-moe": (None, "Not needed: estimate ± margin."),
 "inf-estimate": ("chain", "Sample share on one line, × population size on the next."),
 "stc-general": (None, "Not a calculation."),
 "stc-design": (None, "Not a calculation."),
 "av-area": ("both", "When a length is missing, graph the formula as y = … and y = the given area; click the crossing."),
 "av-perimeter": (None, "Quicker by hand."),
 "av-volume": ("both", "Graph y = (volume formula with x as the missing length) and y = the given volume; click the crossing."),
 "av-surface": (None, "Add the faces by hand; use Desmos only as a calculator."),
 "av-scale": ("chain", "Scale factor k on one line, then k² for areas or k³ for volumes."),
 "lat-parallel": (None, "Angle rules by hand are faster."),
 "lat-lines": (None, "Angle rules by hand are faster."),
 "lat-triangle": ("both", "If the angles are expressions in x, graph their sum and y = 180; click the crossing."),
 "lat-similar": ("both", "Write the proportion with x as the unknown side and graph both sides."),
 "rtt-pythag": (None, "Use it as a calculator for √(a² + b²); check for 3-4-5 and 5-12-13 first."),
 "rtt-trig": (None, "Degree mode. sin(37) and friends work directly; arcsin finds an angle."),
 "rtt-complement": (None, "No calculation: sin x° = cos(90° − x°)."),
 "rtt-special": (None, "Use the 1 : 1 : √2 and 1 : √3 : 2 patterns; Desmos only for the arithmetic."),
 "rtt-similar": ("both", "Set up the proportion with x as the missing side and graph both sides."),
 "cir-read": ("circle", "Graph y = x² + Dx and y = x² + Ey and read the two vertices (the vertex trick)."),
 "cir-build": ("machine", "Type each choice; the right one draws a circle with the given center and radius."),
 "cir-transform": ("machine", "Graph circle A and each choice; check the center moved and the radius changed as described."),
 "cir-radians": (None, "Multiply by π/180 or 180/π; Desmos only as a calculator."),
 "cir-arc": (None, "Arc = (angle ÷ 360) × 2πr; Desmos only as a calculator."),
 "cir-tangent": ("dots", "Graph the circle and the candidate line; a tangent touches at exactly one point."),
 "cir-geo": (None, "Use radii and angle rules by hand."),
}
